<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>Library for persisting system state to a local JSON file.</Description>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Text.Json" Version="8.0.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SystemStateManager\SystemStateManager.csproj" />
  </ItemGroup>

</Project>
