<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>Library for persisting system state to a local JSON file.</Description>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.IO.FileSystem.AccessControl" Version="5.0.0" Condition="'$(TargetFramework)' == 'netstandard2.0'" />
    <PackageReference Include="System.Threading.AccessControl" Version="9.0.0" Condition="'$(TargetFramework)' == 'netstandard2.0'" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SystemStateManager\SystemStateManager.csproj" />
  </ItemGroup>

</Project>
