name: Continuous Integration

on:
  push:
    branches:
    - 'main'
    paths-ignore:
    - 'doc/**'
    - 'CONTRIBUTING.md'
    - 'README.md'

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Clone
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 # Entire history required by Nerdbank.GitVersioning
    - name: Set up .NET
      uses: actions/setup-dotnet@v2
    - name: Set up MSBuild # Must build via MSBuild because `dotnet build` does not support fakes yet.
      uses: microsoft/setup-msbuild@v1.1
    - name: Restore
      run: dotnet restore
    - name: Build
      run: msbuild SystemStateManager.sln /t:Build /p:Configuration=Release
    - name: Test
      run: dotnet test --configuration Release --no-build --verbosity normal --filter "TestCategory != OmitFromCI & TestCategory != Bug & TestCategory != FeatureRequest"
    - name: Pack
      run: dotnet pack --configuration Release --no-build
    - name: Publish
      run: dotnet nuget push **/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
