name: PR Check

on:
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Set up .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Set up MSBuild # Must build via MSBuild because `dotnet build` does not support fakes yet.
      uses: microsoft/setup-msbuild@v1.1
    - name: Clone
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 # Entire history required by Nerdbank.GitVersioning
    - name: Restore
      run: dotnet restore
      env:
        GITHUB_PACKAGE_PAT: ${{ secrets.PACKAGE_READ_PAT }}
    - name: Build
      run: msbuild SystemStateManager.sln /t:Build /p:Configuration=Release
    - name: Test
      run: dotnet test --configuration Release --no-build --verbosity normal --filter 'TestCategory != OmitFromCI & TestCategory != Bug & TestCategory != MissingFeature'
    - name: Pack
      run: dotnet pack --configuration Release --no-build
